---
title: Forecast reconciliation
subtitle: 3. Temporal & cross-temporal forecast reconcilation
author: Rob J Hyndman
pdf-engine: pdflatex
fig-width: 9
fig-height: 4.5
format:
  beamer:
    theme: monash
    aspectratio: 169
    fontsize: 14pt
    section-titles: false
    knitr:
      opts_chunk:
        dev: "CairoPDF"
include-in-header: header.tex
cite-method: biblatex
bibliography: hts.bib
biblio-title: References
keep-tex: true
execute:
  echo: false
  message: false
  warning: false
  cache: true
---

```{r}
source("setup.R")
```

## Outline

\vspace*{0.4cm}\tableofcontents

## Notation reminder

* Data: $\bm{y}_t = \bm{S}\bm{b}_t$ where $\bm{S}$ is a summing matrix and $\bm{b}_t$ is a vector of disaggregated time series
* Base forecasts: $\hat{\bm{y}}_{T+h|T}$
* Reconciled forecasts: $\tilde{\bm{y}}_{T+h|T}=\bS\bm{G}\hat{\bm{y}}_{T+h|T}$
* MinT: $\bG = (\bS'\bm{W}_h^{-1}\bS)^{-1}\bS'\bm{W}_h^{-1}$ where $\bm{W}_h$ is covariance matrix of base forecast errors.


## Temporal reconciliation

\only<1>{\begin{tikzpicture}
\tikzstyle{every node}=[ellipse,draw,inner sep=0.2pt,fill=red!15,font=\small]
\tikzstyle[level distance=.1cm]
\tikzstyle[sibling distance=7cm]
\tikzstyle{level 1}=[sibling distance=72mm,set style={{every node}+=[fill=blue!15]}]
\tikzstyle{level 2}=[sibling distance=36mm,set style={{every node}+=[fill=yellow]}]
\tikzstyle{level 3}=[sibling distance=12mm,font=\scriptsize,set style={{every node}+=[fill=green]}]
\node{Annual}[edge from parent fork down]
 child {node {Semi-Annual$_1$}
   child {node {Q$_1$}
     child {node {\scriptsize M$_1$}}
     child {node {\scriptsize M$_2$}}
     child {node {\scriptsize M$_3$}}
   }
   child {node {Q$_2$}
     child {node {\scriptsize M$_4$}}
     child {node {\scriptsize M$_5$}}
     child {node {\scriptsize M$_6$}}
   }
 }
 child {node {Semi-Annual$_2$}
   child {node {Q$_3$}
     child {node {\scriptsize M$_7$}}
     child {node {\scriptsize M$_8$}}
     child {node {\scriptsize M$_9$}}
   }
   child {node {Q$_4$}
     child {node {\scriptsize M$_{10}$}}
     child {node {\scriptsize M$_{11}$}}
     child {node {\scriptsize M$_{12}$}}
   }
 };
\end{tikzpicture}}
\only<2->{\begin{tikzpicture}
\tikzstyle{every node}=[ellipse,draw,inner sep=0.2pt,fill=red!15,font=\small]
\tikzstyle[level distance=.1cm]
\tikzstyle[sibling distance=7cm]
\tikzstyle{level 1}=[sibling distance=48mm,set style={{every node}+=[fill=blue!15]}]
\tikzstyle{level 2}=[sibling distance=24mm,set style={{every node}+=[fill=yellow]}]
\tikzstyle{level 3}=[sibling distance=12mm,set style={{every node}+=[fill=green]}]
\node{Annual}[edge from parent fork down]
 child {node {FourM$_1$}
   child {node {BiM$_1$}
     child {node {\scriptsize M$_1$}}
     child {node {\scriptsize M$_2$}}
   }
   child {node {BiM$_2$}
     child {node {\scriptsize M$_3$}}
     child {node {\scriptsize M$_4$}}
   }
 }
 child {node {FourM$_2$}
   child {node {BiM$_3$}
     child {node {\scriptsize M$_5$}}
     child {node {\scriptsize M$_6$}}
   }
   child {node {BiM$_4$}
     child {node {\scriptsize M$_7$}}
     child {node {\scriptsize M$_8$}}
   }
 }
  child {node {FourM$_3$}
   child {node {BiM$_5$}
     child {node {\scriptsize M$_9$}}
     child {node {\scriptsize M$_{10}$}}
   }
   child {node {BiM$_6$}
     child {node {\scriptsize M$_{11}$}}
     child {node {\scriptsize M$_{12}$}}
   }
 };
\end{tikzpicture}}\pause

\vspace*{10cm}

\only<3>{\begin{textblock}{12}(2,7)
\begin{alertblock}{}
\begin{itemize}
\item[\color{white}\ding{229}] Forecast series at each available frequency.
\item[\color{white}\ding{229}] Optimally combine forecasts within the same year.
\end{itemize}
\end{alertblock}
\end{textblock}}

## Temporal reconciliation
\fontsize{14}{15}\sf

For a time series  $y_1,\dots,y_T$, observed at frequency $m$, we generate aggregate series
\begin{alertblock}{}\vspace*{-0.1cm}
\[
y_j^{\left[k\right]} = \sum^{jk}_{t=1+(j-1)k}{y_t},\qquad \text{for $j = 1,\dots,\lfloor T/k\rfloor$}
\]
\end{alertblock}
* $k \in F(m)=\{\text{factors of $m$}\}$.
* A single unique hierarchy is only possible when there are no coprime pairs in $F(m)$.
* $M_k=m/k$ is seasonal period of aggregated series.
* Proposed by Athanasopoulos, Hyndman, Kourentzes, Petropoulos (*EJOR*, 2017)

## Cross-temporal reconciliation

\begin{block}{}
\begin{itemize}
\item Kourentzes, Athanasopoulos (\emph{ATR}, 2019)
\item Punia, Singh, Madaan (\emph{C\&IE}, 2020)
\item Di Fonzo,  Girolimetto (2020)
\end{itemize}
\end{block}\pause

\begin{alertblock}{ISF talks coming up!}
\begin{itemize}
\item[\ding{229}] Mitch O'Hara-Wild: \emph{Probabilistic cross-temporal hierarchies in fable} (in about 3 hours)
\item[\ding{229}] Tommi Di Fonzo: \emph{Non-negative cross-temporal forecast reconciliation. An application to the Australian domestic tourism flows} (in about 11 hours).
\end{itemize}
\end{alertblock}

\vspace*{10cm}

## Thief

* thief paper

## Daniele and Tommy's papers

\nocite{Di_FonGir2022a,temporal-hierarchies}
